#!/bin/bash
Z80PACK=~/stuff/z80pack-1.37/cpmsim
XIOSDIR=${PWD}
DRIVE=j
DISK="-f z80pack-hd disks/drive${DRIVE}.dsk"

set -e

cd ${Z80PACK}
cpmrm ${DISK} 0:xios.spr
cpmcp ${DISK} ${XIOSDIR}/xios.spr 0:

UCDRIVE=$(echo ${DRIVE} | tr '[a-z]' '[A-Z]')
sed -e s/--DRIVE--/${UCDRIVE}/ << EOF | expect
spawn ./cpm2
expect "A>"
send "--DRIVE--:\r"
expect "--DRIVE-->"
send "era bnkxios.spr\r"
expect "--DRIVE-->"
send "a:pip bnkxios.spr=xios.spr\r"
expect "--DRIVE-->"
send "gensys \\\$a\r"
expect "--DRIVE-->"
send "a:bye\r"
EOF

echo

if [ -e ${XIOSDIR}/mpm.sys ] ; then
    cpmcp ${DISK} 0:mpm.sys /tmp/.
    STATUS=$(cmp /tmp/mpm.sys ${XIOSDIR}/mpm.sys > /dev/null ; echo $? ; true)
    if [ ${STATUS} -eq 0 ] ; then
	echo "#################"
	echo mpm.sys was not regenerated
	echo "#################"
	exit 1
    fi
fi
cp /tmp/mpm.sys ${XIOSDIR}/.
