#!/bin/bash
Z80PACK=~/stuff/z80pack-1.37/cpmsim
XIOSDIR=${PWD}
DISK="-f z80pack-hd disks/drivei.dsk"

set -e

cd ${Z80PACK}
cpmrm ${DISK} 0:xios.spr
cpmcp ${DISK} ${XIOSDIR}/xios.spr 0:

expect << EOF
spawn ./cpm2
expect "A>"
send "I:\r"
expect "I>"
send "era bnkxios.spr\r"
expect "I>"
send "a:pip bnkxios.spr=xios.spr\r"
expect "I>"
send "gensys \\\$a\r"
expect "I>"
send "a:bye\r"
EOF

echo

cpmcp ${DISK} 0:mpm.sys /tmp/.
STATUS=$(cmp /tmp/mpm.sys ${XIOSDIR}/mpm.sys > /dev/null ; echo $? ; true)
if [ ${STATUS} -eq 0 ] ; then
    echo "#################"
    echo mpm.sys was not regenerated
    echo "#################"
    exit 1
fi
cp /tmp/mpm.sys ${XIOSDIR}/.
