#!/bin/bash

Z80PACK=~/stuff/z80pack-1.37/cpmsim
XIOSDIR=${PWD}
DRIVE=j
DISK="-f z80pack-hd disks/drive${DRIVE}.dsk"

set -e

cd ${Z80PACK}
cpmrm ${DISK} 0:ldrbios.hex
cpmcp -t ${DISK} ${XIOSDIR}/ldrbios.hex 0:

UCDRIVE=$(echo ${DRIVE} | tr '[a-z]' '[A-Z]')
sed -e s/--DRIVE--/${UCDRIVE}/ << EOF | expect
spawn ./cpm2
expect "A>"
send "--DRIVE--:\r"
expect "--DRIVE-->"
send "ddt mpmldr.com\r"
expect -- "-"
send "ildrbios.hex\r"
expect -- "-"
send "r\r"
expect -- "-"
send "g0\r"
expect "--DRIVE-->"
send "save 29 xmpmldr.com\r"
expect "--DRIVE-->"
send "a:bye\r"
EOF

cpmcp ${DISK} 0:xmpmldr.com ${XIOSDIR}/.
